before_script:
   - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
   - cpanm --installdeps . --notest
job1:
  script:
        - prove -lvr t/
        - perl script/orange4 -c config/x86_64-linux-gcc.cnf -t 24
        
